### ISSUE TITLE
When I use microseconds, onFinished isn't triggered

### ISSUE THREAD

**Issue by cesarferreira** [federicodesia/custom_timer#10]
I need a custom duration: `eventDate.difference(DateTime.now())` for the `from`
Yet the `onFinished` wasn't being triggered so I tried to add microseconds to the `from` property and indeed it doesn't trigger it and continue to countdown below 0
```dart
	from: Duration(seconds: 10, microseconds: 11111),
```

```dart
CustomTimer(
  from: Duration(seconds: 10, microseconds: 11111),
  to: Duration(hours: 0),
  onBuildAction: CustomTimerAction.auto_start,
  onFinish: () => _refreshData(),
  builder: (CustomTimerRemainingTime remaining) {
    return Text(
      '${remaining.hours}:${remaining.minutes}:${remaining.seconds}')
    );
  },
)
```

A workaround that works is convert to seconds and convert to Duration
```dart
from: Duration(seconds: Duration(seconds: 10, microseconds: 11111).inSeconds),
```

**Comment by cesarferreira** [comment]
related to #8

**Comment by federicodesia** [comment]
Hello! sorry for the inactivity.
I have updated the package fixing several of the problems that had appeared.

Closing for now, but if the problem continues please let me know!
Thank you very much for helping to improve this package! 🚀
