### ISSUE TITLE
milliseconds not working

### ISSUE THREAD

**Issue by DjamikTea** [federicodesia/custom_timer#11]
`CustomTimer(
                  from: Duration(milliseconds: 0),
                  to: Duration(hours: 1),
                  onBuildAction: CustomTimerAction.auto_start,
                  builder: (CustomTimerRemainingTime remaining) {
                    return Text(
                      "${remaining.minutes}:${remaining.seconds}:${remaining.milliseconds}     ",
                      style: TextStyle(fontSize: 20.0),
                    );
                  },
                ),`

https://user-images.githubusercontent.com/34600049/128942222-1531381f-2b6e-491e-b1e6-0e3bb7c07b93.mov

**Comment by federicodesia** [comment]
Hello! sorry for the inactivity.
I have updated the package fixing several of the problems that had appeared.

Closing for now, but if the problem continues please let me know!
Thank you very much for helping to improve this package! 🚀
