### ISSUE TITLE
usage:

### ISSUE THREAD

**Issue by abdulahadfolio** [federicodesia/custom_timer#12]
how to do something like in a soccer match where you go from 00:00 to 10:95 to 45.00 and so and so ! is this possible?

**Comment by federicodesia** [comment]
Hello! Right now the package does not allow to dynamically change the start and end duration, as well as the current time.
I will try in the future to add these features.

**Comment by federicodesia** [comment]
Currently the package does not allow to do what you mention.
In future versions I will work to add a new feature that allows you to modify the current time.
If you have any idea feel free to send pr!

**Comment by federicodesia** [comment]
Hi @abdulahadfolio! I recently updated this package to fix issues and add features.
I recommend you read the README to see the new way it works after certain important changes.

If you want to achieve something like a soccer game, you can define a controller from 0 to 45 minutes like this:
```dart
late CustomTimerController _controller = CustomTimerController(
  vsync: this,
  begin: Duration(),
  end: Duration(minutes: 45)
);
```

And then you can listen for state changes to detect when the timer finishes and set a new `begin` and `end`:
```dart
_controller.state.addListener(() {
  final state = _controller.state.value;
  if(state == CustomTimerState.finished) {
    _controller.begin = Duration(minutes: 45);
    _controller.end = Duration(minutes: 90);
    _controller.start();
  }
});
```
