### ISSUE TITLE
Controller is dispose after state is finished

### ISSUE THREAD

**Issue by BrianMwas** [federicodesia/custom_timer#13]
I am trying to set up a countdown timer but it keeps throwing an error. Controller is already disposed here's my code
```
CustomTimer(
    controller: controller,
    begin: Duration(seconds: 30),
    end: Duration(seconds: 0),
    onChangeState: (s) {
      if(s == CustomTimerState.finished) {
        print("We completed finished");
        // Prevent calling setState during a widget build
        showTimer.value = false;
        controller.reset();
      }
    },
    builder: (remaining) {
      return Text("${remaining.minutes}:${remaining.seconds}", style: TextStyle(
        fontFamily: "Montserrat",
        fontWeight: FontWeight.w600,
        color: primaryColor,
        fontSize: 14,
      ));
    },
  ),
```

**Comment by BrianMwas** [comment]
When I call start it throws the following error
A CustomTimerController was used after being disposed.

**Comment by federicodesia** [comment]
Hello! Please provide all the information necessary to replicate the error. 

> When I call start it throws the following error
A CustomTimerController was used after being disposed.

Where are you calling `controller.start`?
Are you calling `controller.dispose()` when you remove the widget from the tree?

**Comment by BrianMwas** [comment]
So what I was doing was using it in a pageview but once I navigated back to the previous page and then went back. It gave the error. I fixed it though but extending the mixin AutomaticKeepAliveMixin to prevent the controller from being disposed during multiple page changes

**Comment by federicodesia** [comment]
The package has been updated to fix this issue, it should no longer be necessary to extend the mixin.
