### ISSUE TITLE
Timer doesn't auto start

### ISSUE THREAD

**Issue by Apollo108** [federicodesia/custom_timer#16]
Hi, previously I used "**onBuildAction: CustomTimerAction.auto_start**", but now it's gone, and the timer doesn't auto start. How to auto start on build without using the external controller?

**Comment by federicodesia** [comment]
Hi! `onBuildAction` was removed in version 0.1.0 to reduce and simplify the use of the package.
Now you can only achieve it by using the external controller like this:

```dart
final _controller = CustomTimerController(
    initialState: CustomTimerState.counting
);
```
