### ISSUE TITLE
Toggle visibility always reset timer

### ISSUE THREAD

**Issue by un-hongly** [federicodesia/custom_timer#19]
I wrapped CustomTimer with Visibility and expected the timer not to reset when I hide/show but the timer always reset.

**Comment by federicodesia** [comment]
Hi! Can you confirm if this issue persists in the latest version of the package?
I recommend you read the README to see the new way it works after certain important changes.

I'll close this for now, but if the problem persists let me know so I can reopen it!
It would also help if you could include a small reproducible example.
