### ISSUE TITLE
Feature:  Would be nice to have onCompleted to take action when the counter reaches the end

### ISSUE THREAD

**Issue by Sureya** [federicodesia/custom_timer#20]
When the counter reaches the end its still in `CustomTimerState.counting`. I would like to take action and update certain state values once the clock hits 00:00:00. What would be the best way to do that please?

**Comment by federicodesia** [comment]
Hi! I recently updated this package fixing some of these issues.
I recommend you read the README to see the new way it works after certain important changes.

Now when the timer reaches the end the state changes to `CustomTimerState.finished`
You can also listen for these state changes like this:

```dart
_controller.state.addListener(() {
  final state = _controller.state.value;
  if(state == CustomTimerState.finished) // Take an action
});
```

**Comment by Sureya** [comment]
Many thanks for this update.
