### ISSUE TITLE
Issue: Classic flutter issue of insane & needless rebuilds eating resources - Propose: Less rebuilds for situations where NOT using milliseconds value of CustomTimerRemainingTime

### ISSUE THREAD

**Issue by ghost** [federicodesia/custom_timer#21]
Love this package, nice and simple & thank you for producing it. Now, I think something important could be improved.

I'm no Flutter pro engineer, mega computer genius, crazy Stephen Hawking intellectual, but rebuilding a widget a million times per second has always since I started learning Flutter been a serious main issue, concern & my arch nemesis and looks like Flutter's also. However it is also necessary IF one is showing milliseconds as part of their timer. I can understand this aspect of the programming. This uses enormous system resources in debug mode.

So my proposal is to include some sort of boolean value updateForMilliseconds or something which uses state and does not rebuild so much when not necessary when not using milliseconds value from timer. If using milliseconds then use the good old stateful widget and rebuild it quickly so user can see milliseconds passing.

I suppose all timers would have this issue and this is why I think this could be very valuable when some don't need rapid updates.

Showing my performance issue
```
class OTPTimer extends StatelessWidget {
  final CustomTimerController timeController;

  const OTPTimer({
    required this.timeController,
    Key? key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return CustomTimer(
        controller: timeController,
        begin: const Duration(minutes: 10),
        end: const Duration(minutes: 0),
        builder: (timeRemaining) {
          return Text(
            "${timeRemaining.hours}:${timeRemaining.minutes}:${timeRemaining.seconds}",
            style: timerStyle(timeRemaining),
          );
        });
  }

  // // Timer time text
  TextStyle timerStyle(CustomTimerRemainingTime timeRemaining) {
    print(int.parse(timeRemaining.secondsWithoutFill));                          // Prints 40-60 times per second (useless in my case)
    // Green indicator text
    if (int.parse(timeRemaining.minutesWithoutFill) > 3) {
      return ThemeEndpoints.infoHeaderPositive();
    }
    // Yellow indicator warning text
    if (int.parse(timeRemaining.minutesWithoutFill) < 3 &&
        int.parse(timeRemaining.minutesWithoutFill) > 1) {
      return ThemeEndpoints.infoHeaderWarning();
    }
    // Red indicator warning text
    return ThemeEndpoints.infoHeaderNegative();
  }
```

**Comment by federicodesia** [comment]
Hi! I recently updated this package fixing some of these issues.
I recommend you read the README to see the new way it works after certain important changes.

Now you can tell the controller the update interval of the timer like this:
```dart
late CustomTimerController _controller = CustomTimerController(
  vsync: this,
  begin: Duration(minutes: 10),
  end: Duration(),
  interval: CustomTimerInterval.seconds // 👈 Minutes, seconds, or milliseconds.
);
```

If you continue to get performance issues please let me know!

**Comment by federicodesia** [comment]
To avoid using `int.parse` you can access the `Duration` of `CustomTimerRemainingTime` as follows:

```dart
TextStyle timerStyle(CustomTimerRemainingTime remaining) {
  final minutes = remaining.duration.inMinutes.remainder(60);
  if(minutes >= 3) return ThemeEndpoints.infoHeaderPositive(); // Green indicator text
  if(minutes >= 1) return ThemeEndpoints.infoHeaderWarning(); // Yellow indicator warning text
  return ThemeEndpoints.infoHeaderNegative(); // Red indicator warning text
}
```

**Comment by ghost** [comment]
Beautiful update and thank you for the code suggestion :)
