### ISSUE TITLE
The timer goes bellow 0

### ISSUE THREAD

**Issue by cesarferreira** [federicodesia/custom_timer#8]
I was expecting the behaviour of `onFinish` to be triggered when it gets to `Duration(seconds: 0)` yet it didn't and it continued to negative values, is this a bug? thanks!

```dart
 Widget _timer() {
    return CustomTimer(
      controller: _timerController,
      from: widget.durationLeft,
      to: Duration(seconds: 0),
      interval: Duration(seconds: 1),
      onFinish: () => widget.onFinish(),
      onBuildAction: CustomTimerAction.auto_start,
      builder: (CustomTimerRemainingTime remaining) {
        return Text('${remaining.hours}:${remaining.minutes}:${remaining.seconds}');
      },
    );
  }
```

**Comment by federicodesia** [comment]
I am testing on the latest version of the package and the callback function works fine for me.
`onFinish: () => print("Finished")`
You may have a problem in the function you are executing? try to simplify it to see if it is a package problem.

**Comment by cesarferreira** [comment]
But is the library supposed to continue after it reaches `Duration.zero` ?

**Comment by federicodesia** [comment]
No, it shouldn't continue.
What is the problem? does the callback function never get executed or does the counter get negative values ​​like in issue #7? 
It is also difficult to solve it because I do not get either of the two problems from the latest version.

**Comment by federicodesia** [comment]
Hello! sorry for the inactivity.
I have updated the package fixing several of the problems that had appeared.

Closing for now, but if the problem continues please let me know!
Thank you very much for helping to improve this package! 🚀
