### ISSUE TITLE
Timer between multiple screens

### ISSUE THREAD

**Issue by vijayb95** [federicodesia/custom_timer#9]
I want to use the same time accessed between multiple screens, The timer is resetting in every screen currently, even when I use the same controller.

And when I come back to the previous screen, two instances of the timer running. 

I want one instance of the timer used across multiple screens, do we have an option for that?

**Comment by federicodesia** [comment]
Hello! sorry for the inactivity.
I have updated the package fixing several of the problems that had appeared.

Closing for now, but if the problem continues please let me know!
Thank you very much for helping to improve this package! 🚀
